# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 30

[[main]]
  name = "Resume"
  parent = "Resources"
  pageRef = "resources/resume"
  weight = 10

[[main]]
  name = "Recommendations"
  parent = "Resources"
  pageRef = "resources/recommendations"
  weight = 20

[[main]]
  name = "Reading list"
  parent = "Resources"
  pageRef = "resources/reading-list"
  weight = 30

[[main]]
  name = "List 100"
  parent = "Resources"
  pageRef = "resources/list-100"
  weight = 40

[[main]]
  name = "Now"
  pageRef = "resources/now"
  weight = 50

[[main]]
  name = "About"
  pageRef = "resources/about"
  weight = 60

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

# [[footer]]
#   name = "Open Analytics"
#   pageRef = ""
#   weight = 30
